name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header
          config_timezone: America/Los_Angeles
          plugin_language: yes
          plugin_stars: yes
          config_order: base.header, languages, stars
          output_action: commit
          token: ${{ secrets.METRICS_TOKEN }}
