name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          base: header
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 10
          plugin_activity_limit: 3
          plugin_activity_filter: push, issue, pr, release
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: Nix, Vue, Shell
          plugin_languages_threshold: 2%
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_repositories: yes
          plugin_repositories_featured: ValiantWind/Chad-Bot, ValiantWind/Roblox-Avatar-Thumbnail-Viewer, ValiantWind/QR-Code-Generator
          plugin_introduction: yes
