name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: ValiantWind/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          base: header
          plugin_achievements: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_languages_details: percentage
          plugin_repositories: yes
          plugin_repositories_featured: ValiantWind/ValiantWind.github.io
          plugin_introduction: yes
